### ISSUE TITLE
Error in content type

### ISSUE THREAD

**Issue by Serge3006** [oeg-upm/wot-hive#14]
When we create a thing description with the type field in the property section we have an error reporting that the type is a URL because of the slash.

**Comment by AndreaCimminoArriaga** [comment]
Please could you provide the TD?

**Comment by Salva5297** [comment]
Below is an example of a TD where this error occurs. Specifically, it occurs in the lines of: 
- "type": "multipart-form/data"
- "type": "text/turle"
The TD is the following:

{
  "@context": [
    "https://www.w3.org/2019/wot/td/v1", 
    {
      "beo": "https://pi.pauwel.be/voc/buildingelement#", 
      "bot": "https://w3id.org/bot#", 
      "brick": "https://brickschema.org/schema/1.1/Brick#", 
      "om": "http://openmetrics.eu/openmetrics#", 
      "props": "https://w3id.org/props#", 
      "rdfs": "http://www.w3.org/2000/01/rdf-schema#", 
      "xsd": "http://www.w3.org/2001/XMLSchema#"
    }
  ], 
  "@id": "data.cogito.iot.linkeddata.es/thing/cogito1212", 
  "@type": [
    "bot:Building", 
    "brick:Building"
  ], 
  "description": "A building element.", 
  "properties": {
    "IfcFile": {
      "forms": [
        {
          "href": "https://example_uri.com/files/cogito1212",
		  "type": "multipart-form/data"
        }
      ]
    }, 
    "RDFUri": {
      "forms": [
        {
          "href": "https://openmetrics.eu/openmetrics#Building_120",
		  "type": "text/turle"
        }
      ]
    }
  }, 
  "security": [
    "no_sec"
  ], 
  "securityDefinitions": {
    "no_sec": {
      "scheme": "nosec"
    }
  }, 
  "title": "cogito1212"
}

**Comment by AndreaCimminoArriaga** [comment]
As commented in the issue #13 the id of the TD is not correct. Once the id of the TD is correct the registration occurs as expected.
