### ISSUE TITLE
Wrong validation errors for TD registration

### ISSUE THREAD

**Issue by egekorkan** [oeg-upm/wot-hive#18]
There are some shacl validation errors upon registration. They can be opened in the TD repo if the shape is wrong in the TD in the first place.

- Using `enum` in data schema. 
- Minimum maximum in data schema. There is also different behavior between number and integer 
- Having `op` anywhere
- Using `rel` in links

I have tried some shacl validators but get different results from each. What is the reference validator and which one is used in this project?

**Comment by AndreaCimminoArriaga** [comment]
Hi @egekorkan, thanks for your feedback. I will review your comments as soon as I'm back from vacation.

**Comment by egekorkan** [comment]
When you say the reference validator, do you mean what is used by wothive or what the community refers to as the reference implementation? It would be nice to have a validator that I can use without installing a software stack, so something that is hosted or dockerized. I have found this: https://github.com/ISAITB/shacl-validator

**Comment by AndreaCimminoArriaga** [comment]
In this case wothive uses the jena validator, I'm not sure if this is a candidate implementation of the standard SHACL which is a W3C standard. Currently, the shapes in the WoT directory where not updated to work with the new TD spec and thus they return always error (for instance, the shapes are expecting to have dct:title but the new context translates the title as td:title).

I agree with you about this `It would be nice to have a validator that I can use without installing a software stack`. I also have this one [Astrea](https://astrea.linkeddata.es/). Its main functionality is not validating RDF, but it could be used as well for that purpose.
