### ISSUE TITLE
TD retrieval from different hosts

### ISSUE THREAD

**Issue by egekorkan** [oeg-upm/wot-hive#19]
Sending an HTTP GET request to `/api/things` lists all the Things that have been registered. However, if I try to get a specific TD by giving the id, it is possible to do that only if the request contains the same hostname. So if I host the directory in a docker container, there can be this behavior:
- A Thing boots and registers its TD via localhost
- From outside the container I send a GET request to see all the TDs, the previously registered TD is available. Of course, I cannot use localhost from outside the container.
- I request a specific TD from outside the container and I am met with the following error: `TD with given id not found`

I am giving the same id that is used for registration and also the same one that shows up in the TD when I request all the TDs.

**Comment by AndreaCimminoArriaga** [comment]
The new version (0.2.1) solves this issue, for the moment I will leave this issue as open upon confirmation that indeed the issue is solved.

**Comment by egekorkan** [comment]
The new version (0.2.1) solves this issue, for the moment I will leave this issue as open upon confirmation that indeed the issue is solved.
