### ISSUE TITLE
`@context` and prefixes are cleaned upon registration

### ISSUE THREAD

**Issue by egekorkan** [oeg-upm/wot-hive#20]
When I register a TD that has semantic annotations, there seems to be some "cleanup" process going on. More specifically:
- `@context` is cleaned from other vocabularies:
```js
"@context": [
    "https://www.w3.org/2019/wot/td/v1",
    {
        "schema": "http://schema.org"
    }
]
```
becomes simply `"@context": "https://www.w3.org/2019/wot/td/v1"`

- prefixes of JSON keys are cleaned as reported at https://github.com/oeg-upm/wot-hive/issues/17
- prefixes in JSON key values are **not** cleaned but since the context is cleaned, this is an issue as well.

**Comment by AndreaCimminoArriaga** [comment]
The new version (0.2.1) solves this issue, for the moment I will leave this issue as open upon confirmation that indeed the issue is solved.

**Comment by egekorkan** [comment]
The new version (0.2.1) solves this issue, for the moment I will leave this issue as open upon confirmation that indeed the issue is solved.
