### ISSUE TITLE
Readme version badge links to wot-jtd

### ISSUE THREAD

**Issue by egekorkan** [oeg-upm/wot-hive#21]
The badge on the readme about the version looks like this

![grafik](https://user-images.githubusercontent.com/20195407/151172698-d0c0d4c1-eaa5-4215-9636-72918d99efdd.png)

The version is wrong and it is using the version of wot-jtd. It should point to this repository's releases

**Comment by egekorkan** [comment]
Also the star count is wrong

**Comment by AndreaCimminoArriaga** [comment]
Thanks the links where fixed and the badge with the version updated. The stars is just an image, I'm trying to put a dynamic logo, but I think I will just erase the actual one.
