### ISSUE TITLE
Triplestore Communication Errors

### ISSUE THREAD

**Issue by egekorkan** [oeg-upm/wot-hive#22]
I wanted to test the version 0.2.2 in order to close my previous issues. I did not change anything in my code but I get the following response through the HTTP API (curl --location --request GET 'http://localhost:9000/api/things or same with Postman):
```
{
        "code": "WOT-DIR-P", 
        "description": "Internal problem communnicating with remote SPARQL endpoint",
        "detail": "directory.exceptions.RemoteSparqlEndpointException: Internal query has syntax errors: org.apache.jena.query.QueryException: Endpoint returned Content-Type: text/html which is not recognized for SELECT queries"
}   
```

Logs to the console says:
`wothive_1      | 22/01/27 11:15:51 ERROR directory.Directory: ERROR: SELECT DISTINCT ?graph {  GRAPH <hive:management:things> {  ?graph ?p ?o .  } }`

I get the same error when registering a TD with POST or PUT

**Comment by AndreaCimminoArriaga** [comment]
This is not an issue itself is the configuration to the triple store that is failing. I'm preparing an improved docker that will be published next week. This new docker will persist data although the containers are restarted. [You can try it downloading this folder](https://drive.upm.es/s/bjmGFkSZls8qgGo) everything is already setup so you should not get the previous error.

**Comment by egekorkan** [comment]
I have tried different IP addresses to the configurations but none worked. Do you mean the following type of configuration?
```json
{
"updateEnpoint": "http://localhost:4567/sparql",
"queryEnpoint": "http://localhost:4567/sparql",
"queryUsingGET": true
}
```

**Comment by AndreaCimminoArriaga** [comment]
Hi @egekorkan, a recent PR has provided a ready-to-use docker that requires no configuration. You can find it in this [branch](https://github.com/oeg-upm/wot-hive/tree/auroral-dev-branch/docker)
