### ISSUE TITLE
Registration of TD using Service ontology fields fails

### ISSUE THREAD

**Issue by Joralmi** [oeg-upm/wot-hive#27]
Hello Andrea,
We need to check the registration of TDs containing Service ontology fields. It fails with validation error.
I have checked as well using fields from saref4city and geojson ontologies and it also causes trouble.
We might check this together in the context of AURORAL project

**Comment by AndreaCimminoArriaga** [comment]
Hi Jorge,
I think this may be cause due to the JSON schema of the TDs that is not prepared for receiving these fields. This does not happen with shapes. Let's discuss it in our next meeting
