### ISSUE TITLE
tdd-things-list-pagination-collection

### ISSUE THREAD

**Issue by wiresio** [oeg-upm/wot-hive#28]
Since I'm interested in a second implementation of [108: tdd-things-list-pagination-collection](https://w3c.github.io/wot-discovery#tdd-things-list-pagination-collection) I would be volunteering to provide this for WoT-Hive.

Could you please give me a pointer where the appropriate code should be put? I'd then try to implement it and make a PR.

**Comment by wiresio** [comment]
`ThingsController.listing` ?

**Comment by AndreaCimminoArriaga** [comment]
@wiresio you are right, `ThingsController.listing` is where the current listing is implemented. Maybe create a `ThingsController.altListing` function that is provided under the path `/list`

**Comment by wiresio** [comment]
Addressed by: https://github.com/oeg-upm/wot-hive/pull/29
