### ISSUE TITLE
Merging type and @type in one array

### ISSUE THREAD

**Issue by xdraho11** [oeg-upm/wot-hive#34]
Affected TD

{
  "td": {
    "id": "9d35b43b-7416-431d-a046-6e098c012cf9",
    "geo:location": {
      "geo:lat": "48.1516",
      "geo:long": "17.1674"
    },
    "adapterId": "evchargers-01",
    "securityDefinitions": {
      "nosec_sc": {
        "scheme": "nosec"
      }
    },
    "description": "Service returning EV_chargers for given location",
    "properties": {
      "getChargersForLocation": {
        "type": "number",
        "@type": "adp:AmbientTemperature",
        "readOnly": true,
        "description": "Chargers ",
        "forms": [
          {
            "op": "readproperty",
            "href": "http://adapter:4000/api/v1/chargers"
          }
        ],
        "title": "getChargersForLocation"
      }
    },
    "title": "EV_chargers",
    "@context": [
      "https://www.w3.org/2019/wot/td/v1",
      {
        "adp": "https://auroral.iot.linkeddata.es/def/adapters#",
        "om": "http://www.ontology-of-units-of-measure.org/resource/om-2/",
        "geo": "http://www.w3.org/2003/01/geo/wgs84_pos#"
      },
      "https://www.w3.org/2022/wot/discovery"
    ],
    "security": [
      "nosec_sc"
    ],
    "@type": [
      "adp:Device"
    ]
  }
}

**Comment by AndreaCimminoArriaga** [comment]
Solved after talking with @xdraho11
